/**
 * Build script for generating index.html with dynamic SEO tags.
 * 
 * Usage: node build-index.js
 * 
 * Reads configuration from config/config.json and generates hreflang tags
 * dynamically based on supported languages.
 */

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, '..');
const CONFIG_PATH = path.join(ROOT_DIR, 'config/config.json');
const INDEX_PATH = path.join(ROOT_DIR, 'index.html');

function build() {
    try {
        // Read config
        if (!fs.existsSync(CONFIG_PATH)) {
            console.error('Config file not found!');
            process.exit(1);
        }

        const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
        const baseUrl = config.seo?.baseUrl || 'https://example.com';
        const defaultLanguage = config.i18n?.defaultLanguage || 'it';
        const supportedLanguages = config.i18n?.supportedLanguages || ['en', 'it'];

        console.log(`Generating index.html hreflang tags...`);
        console.log(`Base URL: ${baseUrl}`);
        console.log(`Default language: ${defaultLanguage}`);
        console.log(`Supported languages: ${supportedLanguages.join(', ')}\n`);

        // Read current index.html
        let html = fs.readFileSync(INDEX_PATH, 'utf8');

        // Generate hreflang block
        const hreflangLines = generateHreflangTags(baseUrl, defaultLanguage, supportedLanguages);

        // Replace existing hreflang block or insert after title
        const hreflangBlock = `    <!-- Canonical and Hreflang (auto-generated by build-index.js) -->\n${hreflangLines}`;

        // Pattern to match existing hreflang block
        const hreflangPattern = /\s*<!-- Canonical and Hreflang[^>]*-->[\s\S]*?(?=\s*<link rel="stylesheet")/;

        if (hreflangPattern.test(html)) {
            // Replace existing block
            html = html.replace(hreflangPattern, `\n    \n${hreflangBlock}\n    \n`);
        } else {
            // Insert after title
            html = html.replace(
                /(<title>[^<]*<\/title>)/,
                `$1\n    \n${hreflangBlock}\n    `
            );
        }

        // Write updated index.html
        fs.writeFileSync(INDEX_PATH, html, 'utf8');
        console.log('✓ Updated: index.html with hreflang tags');
        console.log('\nBuild complete!');

    } catch (e) {
        console.error('Error updating index.html:', e);
        process.exit(1);
    }
}

function generateHreflangTags(baseUrl, defaultLanguage, supportedLanguages) {
    const lines = [];

    // Canonical (always the default language URL, which is just /)
    lines.push(`    <link rel="canonical" href="${baseUrl}/">`);

    // Hreflang for each supported language
    for (const lang of supportedLanguages) {
        const url = lang === defaultLanguage
            ? `${baseUrl}/`
            : `${baseUrl}/?lang=${lang}`;
        lines.push(`    <link rel="alternate" hreflang="${lang}" href="${url}">`);
    }

    // x-default points to the default language
    lines.push(`    <link rel="alternate" hreflang="x-default" href="${baseUrl}/">`);

    return lines.join('\n');
}

// Run build
build();
